#!/usr/bin/env python3
"""Build Uganda district / sub-county data for the app and the database.

Source: geoBoundaries (https://www.geoboundaries.org), gbOpen release for UGA.
  - Districts:    ADM3, from Wikimedia Commons, CC0 1.0 / public domain
  - Sub-counties: ADM4, from UNHCR Operational Data Portal, CC BY 3.0 IGO
    (attribution required - see the About text in the app / README).

Known limits of the source: district outlines are coarse near some borders
(e.g. the Kampala outline takes in parts of Wakiso, so Kira Division is
listed under Kampala), and districts created after 2023 are missing.
Farmers can always pick their district by hand.

Outputs:
  assets/areas/uganda_areas.json
      Every district and its sub-counties with simplified outlines, for the
      manual picker and for finding the district / sub-county of a GPS
      position on the phone, offline. District outlines are built by joining
      their sub-counties: the sub-county layer is more accurate than the
      district layer (which, for example, puts central Mbarara in Isingiro).
  supabase/migrations/20261004000000_areas.sql
      The districts table (same ids as the app) and the location columns on
      scans and profiles.

Usage (from the repo root; needs `pip install shapely`):
    python3 tool/build_areas.py            # downloads the source files
    python3 tool/build_areas.py --src DIR  # uses ADM3.geojson / ADM4.geojson in DIR
                                           # (full-detail geoBoundaries files)
"""
import argparse
import json
import re
import sys
import urllib.request
from pathlib import Path

from shapely.geometry import shape, mapping
from shapely.ops import unary_union

ROOT = Path(__file__).resolve().parent.parent
# Full-detail files: sub-counties are matched to districts on these, and only
# the bundled output is simplified.
BASE = ("https://media.githubusercontent.com/media/wmgeolab/geoBoundaries/main/"
        "releaseData/gbOpen/UGA/{lvl}/geoBoundaries-UGA-{lvl}.geojson")
# Water bodies the source lists alongside districts.
NOT_DISTRICTS = {"Lake Victoria"}
# Spelling mistakes in the source's district names.
RENAME_DISTRICTS = {"Kalanga": "Kalangala", "Kitagwenga": "Kitagwenda"}
# Sub-counties the coarse district layer puts in the wrong district, with the
# district they belong to. Add to this as tool/areas_to_review.csv is checked.
SUBCOUNTY_DISTRICT = {
    ("Northern Division", "Rubanda"): "Kabale",  # Kabale municipality
    ("Kira Division", "Kampala"): "Wakiso",  # Kira municipality
    ("Bweyogerere Division", "Kampala"): "Wakiso",
    ("Namugongo Division", "Kampala"): "Wakiso",
    ("Kasangati Town Council", "Kampala"): "Wakiso",
    ("Apac", "Kwania"): "Apac",
    ("Atik Division", "Kwania"): "Apac",  # Apac municipality
}
# A sub-county whose biggest overlap with a district is below this goes in
# the review file.
REVIEW_BELOW = 0.6
SIMPLIFY_DEG = 0.002   # ~220 m; enough for "which sub-county am I in"
DECIMALS = 3           # ~110 m coordinate precision in the bundled file


MIGRATION = """\
-- Areas: Uganda districts, and where each scan was made.
-- Generated by tool/build_areas.py - edit the script, not this file.
--
-- Scans and profiles refer to districts by id but without a foreign key on
-- purpose: a phone with a newer district list must never be blocked from
-- uploading its scans.

create table public.districts (
  id    text primary key,  -- slug of the name, e.g. 'mbale'
  name  text not null
);

alter table public.districts enable row level security;

create policy "Anyone can read districts"
  on public.districts for select to anon, authenticated
  using (true);

insert into public.districts (id, name) values
{values}
on conflict (id) do update set name = excluded.name;

-- Where a scan was made. The app sends GPS on a 0.02 degree grid (about 2 km);
-- the column type rounds anything more precise.
alter table public.scans
  add column district_id      text,
  add column subcounty        text,
  add column location_source  text check (location_source in ('gps', 'manual')),
  add column lat              numeric(5, 2),
  add column lng              numeric(5, 2);

create index scans_district_crop_idx
  on public.scans (district_id, crop, label, taken_at);

-- The farmer's home area and location consent.
alter table public.profiles
  add column home_district_id  text,
  add column home_subcounty    text,
  add column location_consent  text check (location_consent in ('gps', 'manual', 'none')),
  add column consent_at        timestamptz;
"""


def load(level: str, src: Path | None) -> dict:
    if src:
        return json.loads((src / f"{level}.geojson").read_text())
    with urllib.request.urlopen(BASE.format(lvl=level), timeout=120) as r:
        return json.load(r)


def slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def rings(geom) -> list[list[float]]:
    """All rings - outlines and holes - as flattened [lng, lat, ...] lists.
    The app tests points with the even-odd rule across every ring, so holes
    (e.g. Wakiso around Kampala) are respected."""
    polys = [geom] if geom.geom_type == "Polygon" else list(geom.geoms)
    out = []
    for p in polys:
        for ring in [p.exterior, *p.interiors]:
            flat = []
            for x, y in ring.coords:
                flat += [round(x, DECIMALS), round(y, DECIMALS)]
            out.append(flat)
    return out


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", type=Path, help="folder with ADM3/ADM4 .geojson")
    args = ap.parse_args()

    adm3 = load("ADM3", args.src)
    adm4 = load("ADM4", args.src)

    districts = {}
    for f in adm3["features"]:
        name = " ".join(f["properties"]["shapeName"].split())
        if name in NOT_DISTRICTS:
            continue
        name = RENAME_DISTRICTS.get(name, name)
        geom = shape(f["geometry"]).buffer(0)
        did = slug(name)
        if did in districts:  # same district split into several features
            districts[did]["geom"] = unary_union([districts[did]["geom"], geom])
        else:
            districts[did] = {"id": did, "name": name, "geom": geom, "subs": {}}

    unplaced = 0
    by_name = {d["name"]: d for d in districts.values()}
    review = []
    for f in adm4["features"]:
        name = " ".join(f["properties"]["shapeName"].split())
        sub = shape(f["geometry"]).buffer(0)
        # The district covering most of the sub-county.
        overlaps = [(d["geom"].intersection(sub).area, d)
                    for d in districts.values() if d["geom"].intersects(sub)]
        if overlaps:
            area, home = max(overlaps, key=lambda o: o[0])
            share = area / sub.area if sub.area else 0
        else:  # e.g. an island outside every outline: nearest district
            home = min(districts.values(), key=lambda d: d["geom"].distance(sub))
            share = 0
            unplaced += 1
        fixed = SUBCOUNTY_DISTRICT.get((name, home["name"]))
        if fixed:
            home = by_name[fixed]
        elif share < REVIEW_BELOW:
            review.append((name, home["name"], round(share, 2)))
        prev = home["subs"].get(name)
        home["subs"][name] = sub if prev is None else unary_union([prev, sub])

    def bbox(g):
        return [round(v, DECIMALS) for v in g.bounds]

    out = []
    for d in sorted(districts.values(), key=lambda d: d["name"]):
        subs = []
        for name in sorted(d["subs"]):
            g = d["subs"][name].simplify(SIMPLIFY_DEG, preserve_topology=True)
            subs.append({"name": name, "bbox": bbox(g), "rings": rings(g)})
        outline = unary_union(list(d["subs"].values())) if d["subs"] else d["geom"]
        outline = outline.buffer(0).simplify(SIMPLIFY_DEG, preserve_topology=True)
        out.append({
            "id": d["id"],
            "name": d["name"],
            "bbox": bbox(outline),
            "rings": rings(outline),
            "subcounties": subs,
        })

    asset = ROOT / "assets/areas/uganda_areas.json"
    asset.parent.mkdir(parents=True, exist_ok=True)
    asset.write_text(json.dumps({
        "source": "geoBoundaries gbOpen UGA ADM3 (CC0) and ADM4 (UNHCR, CC BY 3.0 IGO)",
        "districts": out,
    }, separators=(",", ":")))

    values = ",\n".join(
        "  ('{}', '{}')".format(d["id"], d["name"].replace("'", "''")) for d in out)
    migration = ROOT / "supabase/migrations/20261004000000_areas.sql"
    migration.write_text(MIGRATION.format(values=values))

    review_file = ROOT / "tool/areas_to_review.csv"
    review_file.write_text(
        "# Sub-counties with no clear district in the source (largest overlap\n"
        "# below {:.0%}). Mostly lake/island areas; check the rest with local\n"
        "# knowledge and add corrections to SUBCOUNTY_DISTRICT in build_areas.py.\n"
        "subcounty,assigned_district,overlap_share\n".format(REVIEW_BELOW)
        + "".join(f"{n},{d},{s}\n" for n, d, s in sorted(review, key=lambda r: r[1])))

    subs = sum(len(d["subcounties"]) for d in out)
    empty = [d["name"] for d in out if not d["subcounties"]]
    if empty:
        print(f"districts without sub-counties (source outline used): {empty}",
              file=sys.stderr)
    print(f"{len(out)} districts, {subs} sub-counties "
          f"({unplaced} placed by nearest district, {len(review)} to review), "
          f"{asset.stat().st_size // 1024} KB asset", file=sys.stderr)


if __name__ == "__main__":
    main()
