"""Writes supabase/setup_all.sql: every migration in order, in one file, so a
new Supabase project can be set up with a single paste into the SQL Editor.

    python3 tool/combine_migrations.py

Rerun it after adding a migration.
"""
from pathlib import Path

root = Path(__file__).resolve().parent.parent
migrations = sorted((root / 'supabase' / 'migrations').glob('*.sql'))
parts = [
    '-- MY FARM: complete database setup for a NEW Supabase project.\n'
    '-- Generated by tool/combine_migrations.py from supabase/migrations/.\n'
    '-- Paste all of it into Supabase -> SQL Editor -> New query, then Run.\n'
    '-- Run it once only: on a project that already has the tables it fails.\n'
]
for m in migrations:
    parts.append(f'\n-- ===== {m.name} =====\n\n' + m.read_text().rstrip() + '\n')
parts.append(
    '\n-- ===== check =====\n'
    '-- Should show districts = 136 and treatments = 38.\n'
    'select\n'
    '  (select count(*) from public.districts)  as districts,\n'
    '  (select count(*) from public.treatments) as treatments;\n')
(root / 'supabase' / 'setup_all.sql').write_text(''.join(parts))
print(f'wrote supabase/setup_all.sql from {len(migrations)} migrations')
