-- Initial treatment text, generated from lib/services/treatment_db.dart
-- by tool/export_treatments.py. Edit treatments in the dashboard, not here.
insert into public.treatments (label, lang, cause, organic, chemical, prevent) values
  ('cassava_mosaic_disease',
   'en',
   'A viral disease spread by whiteflies and infected cuttings. Leaves show yellow-green mosaic patterns and become distorted, reducing root yield.',
   'Uproot and burn badly infected plants. Plant only certified disease-free, resistant varieties (e.g. NASE 14, NAROCASS 1). Control whiteflies by keeping fields weed-free.',
   'No chemical cures the virus. Whitefly vectors can be reduced with imidacloprid-based insecticides applied per label, but resistant varieties are the main control.',
   'Always source cuttings from clean, certified plants and remove infected plants early to stop spread.'),
  ('cassava_mosaic_disease',
   'lg',
   'Bulwadde bwa kawuka obusaasaanyizibwa ensekere (whitefly) n’ebikolo ebirwadde. Amakoola gafuna langi eza kyenvu ne kiragala era ne gakyukakyuka.',
   'Kuula okweko ebimera ebirwadde nnyo obyokye. Simba ebika ebigumira obulwadde nga NASE 14 oba NAROCASS 1. Ziyiza ensekere ng’oggyawo omuddo.',
   'Tewali ddagala liwonya kawuka. Ensekere ziyinza okukendeezebwa n’eddagala nga imidacloprid, naye ebika ebigumira bye bisinga.',
   'Funa ebikolo okuva mu bimera ebirongoofu era ggyawo ebirwadde mangu.'),
  ('cassava_brown_streak_disease',
   'en',
   'A viral disease spread by whiteflies. It causes yellow blotches on leaves and brown, rotting streaks inside the roots, often unseen until harvest.',
   'Remove and destroy infected plants. Use tolerant varieties recommended by NaCRRI. Harvest early in high-risk areas to limit root damage.',
   'No chemical cures the virus. Manage whitefly vectors with recommended insecticides; rely mainly on clean planting material and tolerant varieties.',
   'Plant certified tolerant cuttings, control whiteflies, and avoid moving cuttings from affected areas.'),
  ('cassava_brown_streak_disease',
   'lg',
   'Bulwadde bwa kawuka obuva mu nsekere. Buleeta amabala aga kyenvu ku makoola n’obukubo obwa kakobe obuvunda munda mu mizizi.',
   'Ggyawo era ozikirize ebimera ebirwadde. Kozesa ebika ebigumira okuva ku NaCRRI. Kungula amangu mu bitundu ebirimu obulabe.',
   'Tewali ddagala liwonya kawuka. Ddukanya ensekere n’eddagala erikkirizibwa; weesigame ku bikolo ebirongoofu.',
   'Simba ebikolo ebigumira, ziyiza ensekere, era toleeta bikolo kuva mu bitundu ebirwadde.'),
  ('cassava_bacterial_blight',
   'en',
   'A bacterial disease spread by rain splash and tools. Causes angular leaf spots, wilting, dieback and gum on stems, worst in wet weather.',
   'Cut and burn affected shoots. Disinfect tools (e.g. with bleach solution) between plants. Use clean cuttings and practise crop rotation.',
   'Copper-based bactericides (e.g. copper oxychloride at the label rate) can slow spread on young plants. Sanitation and resistant varieties matter most.',
   'Use disease-free cuttings, avoid working in fields when wet, and rotate with non-host crops.'),
  ('cassava_bacterial_blight',
   'lg',
   'Bulwadde bwa bakitiriya obusaasaanyizibwa enkuba n’ebikozesebwa. Buleeta amabala ku makoola, okuwotoka n’envuumuulo ku miti.',
   'Salako era oyokye amatabi agarwadde. Yoza ebikozesebwa wakati w’ebimera. Kozesa ebikolo ebirongoofu era okyuse ebirime.',
   'Eddagala lya copper (nga copper oxychloride) liyinza okukendeeza okusaasaana ku bimera ebito. Obuyonjo n’ebika ebigumira bye bisinga.',
   'Kozesa ebikolo ebitali birwadde, toweereza mu nnimiro nga nnyonyi, era okyuse ebirime.'),
  ('cassava_green_mottle',
   'en',
   'A viral disease causing green mottling and mild leaf distortion. Effects on yield are usually milder than mosaic or brown streak.',
   'Remove visibly affected plants and use clean, certified cuttings. Keep whitefly populations down through good field hygiene.',
   'No chemical cures the virus. Focus on clean planting material and vector management.',
   'Source cuttings from healthy plants and monitor fields regularly for early symptoms.'),
  ('cassava_green_mottle',
   'lg',
   'Bulwadde bwa kawuka obuleeta amabala aga kiragala n’okukyukakyuka okutono ku makoola.',
   'Ggyawo ebimera ebirwadde era okozese ebikolo ebirongoofu. Kuuma ensekere nga ntono.',
   'Tewali ddagala liwonya kawuka. Ssa essira ku bikolo ebirongoofu.',
   'Funa ebikolo okuva mu bimera ebiramu era okebere ennimiro buli kiseera.'),
  ('maize_northern_leaf_blight',
   'en',
   'A fungal disease favoured by humid, cool conditions. Long grey-green to tan cigar-shaped lesions appear on leaves, reducing grain fill.',
   'Rotate maize with non-cereal crops, remove crop residue after harvest, and plant resistant hybrids where available.',
   'Apply a recommended fungicide (e.g. mancozeb or a strobilurin) at first sign and repeat per label if pressure is high.',
   'Use resistant varieties, rotate crops, and avoid dense planting that keeps leaves wet.'),
  ('maize_northern_leaf_blight',
   'lg',
   'Bulwadde bwa kawuka (fungus) olw’obunnyogovu. Buleeta amabala amawanvu ku makoola.',
   'Kyuusa kasooli n’ebirime ebirala, ggyawo ebisigalira, era simba ebika ebigumira.',
   'Kozesa eddagala nga mancozeb ng’obulwadde butandika era oddiremu nga bwe kyetaagisa.',
   'Kozesa ebika ebigumira, kyuusa ebirime, era tosimba kumpi nnyo.'),
  ('maize_common_rust',
   'en',
   'A fungal disease showing small reddish-brown pustules on both leaf surfaces. Severe infection reduces photosynthesis and yield.',
   'Plant resistant hybrids, ensure good spacing for airflow, and remove heavily infected leaves early.',
   'Fungicides such as mancozeb or triazoles control rust when applied early per label.',
   'Choose resistant varieties and avoid late planting into cool, moist periods.'),
  ('maize_common_rust',
   'lg',
   'Bulwadde bwa kawuka obulaga obukubo obumyufu ku makoola.',
   'Simba ebika ebigumira, leka ebbanga wakati w’ebimera, era ggyawo amakoola agarwadde.',
   'Eddagala nga mancozeb liyinza okuyamba nga likozesebwa mangu.',
   'Londa ebika ebigumira era tosimba kibula mu budde obunnyogovu.'),
  ('maize_gray_leaf_spot',
   'en',
   'A fungal disease producing rectangular grey lesions bounded by leaf veins, worsened by minimum tillage and continuous maize.',
   'Rotate away from maize, bury residue, and plant tolerant hybrids.',
   'Strobilurin or triazole fungicides applied at early infection reduce spread.',
   'Rotate crops, manage residue, and avoid continuous maize on the same plot.'),
  ('maize_gray_leaf_spot',
   'lg',
   'Bulwadde bwa kawuka obuleeta amabala aga kyenvu-kiragala ku makoola.',
   'Kyuusa okuva ku kasooli, ziika ebisigalira, era simba ebika ebigumira.',
   'Eddagala nga triazole likendeeza okusaasaana nga likozesebwa mangu.',
   'Kyuusa ebirime era toddiŋŋana kusimba kasooli mu kifo kye kimu.'),
  ('tomato_late_blight',
   'en',
   'A fast-moving fungal-like disease in cool, wet weather. Dark water-soaked blotches spread on leaves and fruit, destroying crops within days.',
   'Remove and destroy infected plants immediately. Improve airflow, avoid overhead watering, and never compost infected material.',
   'Apply copper oxychloride (about 3 g/L) or mancozeb every 7 days during wet weather, following the label.',
   'Use resistant varieties, space plants well, water at the base, and scout daily in wet spells.'),
  ('tomato_late_blight',
   'lg',
   'Bulwadde obw’amaanyi mu budde obunnyogovu. Buleeta amabala amaddugavu ku makoola ne ku bibala ne bizikiriza ebimera.',
   'Ggyawo era ozikirize ebimera ebirwadde mangu. Tofukirira kungulu, era tokozesa ebirwadde mu bolovu.',
   'Kozesa copper oxychloride (3g/L) oba mancozeb buli nnaku 7 mu budde obunnyogovu.',
   'Kozesa ebika ebigumira, leka ebbanga, fukirira wansi, era okebere buli lunaku.'),
  ('tomato_early_blight',
   'en',
   'A fungal disease causing dark concentric-ring spots on older leaves, leading to defoliation and sun-scalded fruit.',
   'Remove lower infected leaves, mulch to stop soil splash, and rotate away from tomato and potato.',
   'Mancozeb or chlorothalonil applied per label at first symptoms limits spread.',
   'Rotate crops, mulch, stake plants, and avoid wetting leaves when watering.'),
  ('tomato_early_blight',
   'lg',
   'Bulwadde bwa kawuka obuleeta amabala ag’empeta ku makoola amakulu.',
   'Ggyawo amakoola ag’emmanga agarwadde, ssaako omuddo, era okyuse ebirime.',
   'Mancozeb oba chlorothalonil nga bukozesebwa mangu kukendeeza okusaasaana.',
   'Kyuusa ebirime, ssaako omuddo, simba ku miti, era tonnyikiza makoola.'),
  ('tomato_leaf_mold',
   'en',
   'A fungal disease of humid conditions. Pale yellow spots appear on upper leaf surfaces with olive mould beneath.',
   'Increase ventilation, reduce humidity, and remove affected leaves. Avoid crowding plants.',
   'Copper or mancozeb fungicides applied per label help in persistent cases.',
   'Space and prune plants for airflow and keep humidity down, especially under cover.'),
  ('tomato_leaf_mold',
   'lg',
   'Bulwadde bwa kawuka mu budde obunnyogovu. Amabala aga kyenvu ku makoola.',
   'Yongera empewo, kendeeza obunnyogovu, era ggyawo amakoola agarwadde.',
   'Eddagala lya copper oba mancozeb liyamba mu mbeera enkalubo.',
   'Leka ebbanga era osaleko ebimera, era kendeeza obunnyogovu.'),
  ('tomato_septoria_leaf_spot',
   'en',
   'A fungal disease causing many small circular spots with grey centres on lower leaves, spreading upward.',
   'Remove infected leaves, mulch, and rotate crops. Avoid working with plants when wet.',
   'Chlorothalonil or mancozeb applied per label slows progression.',
   'Rotate, mulch, stake plants, and water at the base only.'),
  ('tomato_septoria_leaf_spot',
   'lg',
   'Bulwadde bwa kawuka obuleeta obubala obutono obungi ku makoola ag’emmanga.',
   'Ggyawo amakoola agarwadde, ssaako omuddo, era okyuse ebirime.',
   'Chlorothalonil oba mancozeb kukendeeza okusaasaana.',
   'Kyuusa, ssaako omuddo, simba ku miti, era fukirira wansi.'),
  ('tomato_yellow_leaf_curl_virus',
   'en',
   'A viral disease spread by whiteflies. Leaves curl upward, yellow and shrink, and plants are stunted with poor fruit set.',
   'Remove infected plants, control whiteflies with yellow sticky traps and field hygiene, and use resistant varieties.',
   'No chemical cures the virus. Reduce whitefly vectors with recommended insecticides; resistant varieties are key.',
   'Plant resistant varieties, control whiteflies early, and remove infected plants promptly.'),
  ('tomato_yellow_leaf_curl_virus',
   'lg',
   'Bulwadde bwa kawuka obuva mu nsekere. Amakoola gewamba, gafuuka kyenvu, era ebimera tebikula bulungi.',
   'Ggyawo ebimera ebirwadde, ziyiza ensekere, era kozesa ebika ebigumira.',
   'Tewali ddagala liwonya kawuka. Kendeeza ensekere n’eddagala erikkirizibwa.',
   'Simba ebika ebigumira, ziyiza ensekere mangu, era ggyawo ebirwadde.'),
  ('maize_lethal_necrosis',
   'en',
   'A viral disease (MCMV combined with a potyvirus) spread by insects and infected seed. Leaves show yellow mottling and dead streaks, plants are stunted, and cobs are small or empty.',
   'Uproot and destroy infected plants early. Plant clean, certified seed of tolerant varieties. Practise a closed season and rotate with non-cereal crops (e.g. beans) to break the cycle.',
   'No chemical cures the virus. Reduce insect vectors (thrips, beetles) with a recommended insecticide per label, but clean seed, tolerant varieties and rotation are the main controls.',
   'Use certified seed, avoid continuous maize on the same land, control insect vectors and remove volunteer maize plants between seasons.'),
  ('maize_lethal_necrosis',
   'lg',
   'Bulwadde bwa kawuka (MCMV ne potyvirus) obusaasaanyizibwa ebiwuka n’ensigo ezirwadde. Amakoola gafuna langi eya kyenvu n’obukubo obufu, ebimera tebikula, n’ebigombe biba bitono.',
   'Kuula era ozikirize ebimera ebirwadde amangu. Simba ensigo ennongoofu ez’ebika ebigumira. Wummuza ennimiro era okyuse n’ebirime ebirala nga ebijanjaalo.',
   'Tewali ddagala liwonya kawuka. Kendeeza ebiwuka n’eddagala erikkirizibwa, naye ensigo ennongoofu n’ebika ebigumira bye bisinga.',
   'Kozesa ensigo ennongoofu, tolima kasooli buli mwaka mu ttaka limu, ziyiza ebiwuka era ggyawo kasooli eyeemezeemeze.'),
  ('maize_streak_virus',
   'en',
   'A viral disease spread by leafhoppers. Leaves show long, pale yellow-to-white broken stripes running along the veins; infected young plants are badly stunted.',
   'Remove and destroy infected plants. Plant early and synchronise planting with neighbours to avoid leafhopper peaks. Grow streak-resistant varieties recommended locally.',
   'No chemical cures the virus. Leafhopper numbers can be lowered with a recommended systemic insecticide per label, but resistant varieties and early planting are the main control.',
   'Use resistant varieties, plant early in the season, control grassy weeds that host leafhoppers, and remove infected plants quickly.'),
  ('maize_streak_virus',
   'lg',
   'Bulwadde bwa kawuka obuva mu biwuka (leafhoppers). Amakoola galaga obukubo obuwanvu obwa kyenvu oba obweru nga bugoberera emisuwa; ebimera ebito birwala nnyo.',
   'Ggyawo era ozikirize ebimera ebirwadde. Simba amangu era simba awamu ne baliraanwa okwewala ebiwuka. Simba ebika ebigumira obulwadde.',
   'Tewali ddagala liwonya kawuka. Ebiwuka biyinza okukendeezebwa n’eddagala erikkirizibwa, naye ebika ebigumira n’okusimba amangu bye bisinga.',
   'Kozesa ebika ebigumira, simba amangu, ziyiza omuddo oguwa ebiwuka ekifo, era ggyawo ebirwadde amangu.'),
  ('bean_angular_leaf_spot',
   'en',
   'A fungal disease favoured by warm, humid weather. It causes grey-brown angular spots bounded by leaf veins; severe attacks cause early leaf drop and lower pod yield.',
   'Use clean, certified seed and resistant varieties. Rotate beans with non-host crops (e.g. maize) for 2 seasons. Remove and compost crop residues after harvest and avoid working in wet fields.',
   'Where pressure is high, protectant fungicides such as copper-based products or chlorothalonil can be applied per label at early flowering and repeated as directed.',
   'Plant certified seed, rotate crops, give wider spacing for airflow, and avoid overhead irrigation late in the day.'),
  ('bean_angular_leaf_spot',
   'lg',
   'Bulwadde bwa ffene (fungus) obwagalwa obudde obw’ebbugumu n’obunnyogovu. Buleeta amabala aga kyenvu-kakobe agalina enkukunala nga gakomekkerezebwa emisuwa; bwe gweyongera amakoola gagwa.',
   'Kozesa ensigo ennongoofu n’ebika ebigumira. Kyuse ebijanjaalo n’ebirime ebirala (nga kasooli) okumala ebiseera bibiri. Ggyawo ebisigadde era toweereza mu nnimiro ennyogovu.',
   'Bwe wabaawo obulwadde bungi, kozesa eddagala (copper oba chlorothalonil) ng’ekiragiro bwe kigamba, ng’osooka ku kumulisa.',
   'Simba ensigo ennongoofu, kyuse ebirime, ssa ebbanga eggazi era weewale okufukirira waggulu akawungeezi.'),
  ('bean_rust',
   'en',
   'A fungal disease producing small reddish-brown raised pustules (like rust powder) mainly on the underside of leaves. Heavy infection dries leaves and reduces yield.',
   'Plant resistant varieties and certified seed. Remove and destroy infected debris. Give wider spacing to improve airflow and reduce leaf wetness; rotate with cereals.',
   'If rust appears early and spreads, apply a recommended fungicide (e.g. mancozeb or a triazole) per label and repeat at the stated interval.',
   'Use resistant varieties, avoid dense planting, remove crop residues, and scout regularly so spraying starts early if needed.'),
  ('bean_rust',
   'lg',
   'Bulwadde bwa ffene obuleeta obutulututtu obutono obumyufu-kakobe (ng’enfuufu ya butalo) okusinga wansi w’amakoola. Bwe guyitirira amakoola gakala.',
   'Simba ebika ebigumira n’ensigo ennongoofu. Ggyawo era ozikirize ebisigadde ebirwadde. Ssa ebbanga eggazi okuyamba empewo; kyuse n’ebirime ebirala.',
   'Singa obulwadde busooka amangu, kozesa eddagala (mancozeb oba triazole) ng’ekiragiro bwe kigamba era oddiremu.',
   'Kozesa ebika ebigumira, weewale okusimba okunyweera, ggyawo ebisigadde era okebere buli kiseera.'),
  ('banana_black_sigatoka',
   'en',
   'A fungal leaf disease (Pseudocercospora fijiensis) spread by airborne spores in wet conditions. It starts as small dark streaks that merge into large black blotches, killing leaves and shrinking bunches.',
   'Cut off and bury or burn affected leaves (de-leafing). Improve drainage and remove weeds to lower humidity. Maintain wider spacing and grow tolerant cultivars where available.',
   'In severe cases, protectant or systemic fungicides (e.g. mancozeb, or a triazole) may be applied per label; rotate fungicide groups to avoid resistance.',
   'Regular de-leafing of infected leaves, good drainage, proper spacing for airflow, and avoiding movement of infected material between fields.'),
  ('banana_black_sigatoka',
   'lg',
   'Bulwadde bwa ffene ku makoola (Pseudocercospora fijiensis) obusaasaanyizibwa empewo mu budde obunnyogovu. Butandika ng’obukubo obutono obuddugavu ne bugatta ne bufuuka amabala amaddugavu, amakoola ne gafa.',
   'Salako era oziike oba ookye amakoola amalwadde. Longoosa enkulukuto y’amazzi era ggyawo omuddo okukendeeza obunnyogovu. Ssa ebbanga eggazi era simba ebika ebigumira.',
   'Bwe kiba kibi nnyo, kozesa eddagala lya ffene (mancozeb oba triazole) ng’ekiragiro bwe kigamba; kyusa ebika by’eddagala okwewala obukakanyavu.',
   'Salangako amakoola amalwadde buli kiseera, longoosa enkulukuto, ssa ebbanga era toleeta bintu birwadde mu nnimiro.'),
  ('banana_fusarium_wilt',
   'en',
   'A soil-borne fungal disease (Fusarium oxysporum) that blocks the plant’s water channels. Older leaves yellow and collapse around the pseudostem, and cut stems show brown discoloured rings. It persists in soil for years.',
   'There is no cure once a mat is infected. Remove and destroy affected mats, do not move soil or suckers from infected sites, and plant clean suckers of resistant cultivars in unaffected ground. Improve soil health and drainage.',
   'No effective chemical control exists for this soil-borne fungus. Management relies on resistant cultivars, clean planting material and strict field sanitation rather than spraying.',
   'Use disease-free, resistant planting material, disinfect tools, control movement of soil and suckers, and avoid replanting bananas immediately on infected land.'),
  ('banana_fusarium_wilt',
   'lg',
   'Bulwadde bwa ffene obuva mu ttaka (Fusarium oxysporum) obuziyiza amazzi okutambula mu kimera. Amakoola amakulu gakyuka kyenvu ne gagwa ku kikolo, era ssinga osala olaba empeta eza kakobe. Busigala mu ttaka emyaka mingi.',
   'Tewali ddagala liwonya bwe kimera kimaze okulwala. Ggyawo era ozikirize ebimera ebirwadde, toleeta ttaka oba ensukusa okuva mu kifo ekirwadde, era simba ensukusa ennongoofu ez’ebika ebigumira mu ttaka eddongoofu.',
   'Tewali ddagala lirikola ku ffene eno ey’omu ttaka. Weesigame ku bika ebigumira, ebikolo ebirongoofu n’obuyonjo bw’ennimiro.',
   'Kozesa ensukusa ennongoofu ezigumira, yoza ebikozesebwa, ziyiza okutambuza ttaka n’ensukusa, era tosimba bananas mangu mu ttaka eryalimu obulwadde.'),
  ('healthy',
   'en',
   'No disease detected. The plant looks healthy.',
   'Keep up good practices: balanced feeding, proper spacing, weeding, and regular scouting.',
   'No treatment needed. Continue routine monitoring.',
   'Maintain field hygiene and inspect plants regularly to catch any problem early.'),
  ('healthy',
   'lg',
   'Tewali bulwadde bulabise. Ekimera kiramu bulungi.',
   'Weeyongere okukola obulungi: okuliisa, ebbanga, okukuula, n’okukebera.',
   'Tewali ddagala lyetaagisa. Weeyongere okukebera.',
   'Kuuma obuyonjo era okebere ebimera buli kiseera.')
on conflict (label, lang) do nothing;
